# Generated by Django 4.0.3 on 2022-03-12 01:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('email', models.TextField(default='', max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('_id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('upvotes', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=25, max_digits=30)),
                ('lon', models.DecimalField(decimal_places=25, max_digits=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapnotes.user')),
                ('map_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapnotes.map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapnotes.user'),
        ),
    ]
