# Generated by Django 4.0.3 on 2022-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.TextField(max_length=320, primary_key=True, serialize=False),
        ),
    ]
