# Generated by Django 4.0.3 on 2022-03-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='lat',
            field=models.DecimalField(decimal_places=25, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='note',
            name='lon',
            field=models.DecimalField(decimal_places=25, default=0.0, max_digits=30),
        ),
    ]
