# Generated by Django 4.0.3 on 2022-03-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.TextField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
