# Generated by Django 4.0.3 on 2022-03-14 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapnotes', '0002_remove_user_email_alter_user__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default='', max_length=320),
        ),
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
