# Generated by Django 4.0.3 on 2022-03-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapnotes', '0002_remove_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
